version: "3"

services:
  minimart_db:
    image: "postgres"
    container_name: "minimart_db"
    restart: always
    environment:
      - POSTGRES_USER=secretdbuser
      - POSTGRES_PASSWORD=secretdbpass
      - POSTGRES_DB=minimart_db
    ports:
      - "5432:5432"
    # volumes:
      # - ./postgres-data:/var/lib/postgresql/data
  
  minimart_api:
    build: .
    container_name: "minimart_api"
    restart: always
    environment:
      - DB_HOST=minimart_db
      - DB_PORT=5432
      - DB_USER=secretdbuser
      - DB_PASS=secretdbpass
    ports:
      - "9988:9988"